export enum Messages {
  FAILED_TO = 'Failed to',
  NOT_FOUND = 'data not found.',
  ID_NOT_FOUND = 'Id not found.',
  ALREADY_EXIST = 'already exist.',
  DOES_NOT_MATCH = `doesn't match.`,
  UPDATE_FAILED = 'Your password is not update.',
  SEND_SUCCESS = 'send successfully.',
  PASSWORD_NOT_MATCH = 'Current password and new password cannot be same.',
  INCORRECT_PASSWORD = 'Old password is incorrect.',
  ADD_SUCCESS = 'added successfully.',
  UPDATE_SUCCESS = 'updated successfully.',
  DELETED_SUCCESS = 'deleted successfully.',
  GET_SUCCESS = 'getting successfully.',
  CREDENTIAL_NOT_MATCH = `Credentials does not match.`,
  LOGIN_SUCCESS = 'You are login successfully.',
  EMAIL_INCORRECT = 'Your email is not registered.',
  OTP_EXPIRED = 'Your OTP is expired.',
  OTP_NOT_MATCH = 'Please enter correct otp.',
  NOT_SELECTED = 'No file selected.',
  IS_REQUIRED = 'is required.',
}
